### ISSUE TITLE
Multi-screen Multi-resolution creates flicker upon change. 

### ISSUE THREAD

**Issue by HighOnVoltage** [Simonmicro/better-backgrounds#17] opened 2021-07-02 10:26 UTC
Thanks for your work Simon! 

Just got a little issue when the background changes/transition the images don't quite line up causing a flicking effect. 

Not an expert, nor a coder but looking over the applet this might be an upstream issue with Cinnamon as I couldn't clearly define the problem in your code. Any help from a newbie is appreciative!

- Trev

**Comment by simonmicro** [comment] 2021-07-02 21:10
Hmm, this could be indeed an upstream issue with Cinnamon or your graphics drivers. :coffee: 

Please make sure the image generated by this applet is correct: For that you just have to open the save location and open the image in a viewer of your choice - are any artifacts there? Does the viewer report a damaged file?

This applet does not handle the background transition by itself - it just swaps the currently selected file and then instructs Cinnamon to re-apply the image. There is a very tiny chance, that Cinnamon notices this swap and tries to transition, before the file is fully written (meh, file operations are atomic - so this is just a wild guess)... Therefore what happens when you restart cinnamon (CRTL+ALT+ESC, make sure the applet does not change on reload for this)? Is the image then correct?

What happens when you select a folder with multiple images and let Cinnamon create a slideshow of it - does this issue also appear there (and without the applet)? If yes, this is a hint that Cinnamon itself messes up the transitions!

**Comment by simonmicro** [comment] 2022-03-28 12:43
Thanks for this issue report, but up until today I was not able to reproduce this or get any other report about this. Feel free to reopen, but for now I'll close this issue.

**Closed as completed by simonmicro** 2022-03-28 12:43 UTC
Labels: help wanted

**Comment by HighOnVoltage** [comment] 2023-06-01 13:21
Whatever the latest code update has resolved my issue with the flicking and how my taskbar wasn't correct. 

My hardware is a Lenovo W530 and goes to show how long our electronics and solid linux software can correct itself. I believe I initially installed not far from my additionally installation date. Cheers @simonmicro for checking it out.
